//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carcassonne_Desktop.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Carcassonne_Desktop.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt; 
        ///&lt;carcassonne&gt;
        ///  &lt;tile number=&quot;1&quot;&gt;
        ///
        ///    &lt;city id=&quot;0&quot;&gt;
        ///      &lt;openings&gt;3&lt;/openings&gt;
        ///      &lt;flags&gt;0&lt;/flags&gt;
        ///      &lt;texture&gt;city&lt;/texture&gt;
        ///    &lt;/city&gt;
        ///    &lt;farm id=&quot;1&quot;&gt;
        ///      &lt;neighbor_city&gt;0&lt;/neighbor_city&gt;
        ///      &lt;texture&gt;farm&lt;/texture&gt;
        ///    &lt;/farm&gt;
        ///    &lt;farm id=&quot;2&quot;&gt;
        ///      &lt;neighbor_city&gt;0&lt;/neighbor_city&gt;
        ///      &lt;texture&gt;farm&lt;/texture&gt;
        ///    &lt;/farm&gt;
        ///    &lt;road id=&quot;3&quot;&gt;
        ///      &lt;openings&gt;1&lt;/openings&gt;
        ///      &lt;texture&gt;road&lt;/texture&gt;
        ///    &lt;/road&gt;
        ///
        ///    &lt;direction [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _10Tiles {
            get {
                return ResourceManager.GetString("_10Tiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;carcassonne&gt;
        ///
        ///  &lt;tile number=&quot;1&quot;&gt;
        ///
        ///    &lt;city id=&quot;0&quot;&gt;
        ///      &lt;openings&gt;4&lt;/openings&gt;
        ///      &lt;flags&gt;1&lt;/flags&gt;
        ///      &lt;texture&gt;city&lt;/texture&gt;
        ///    &lt;/city&gt;
        ///
        ///    &lt;direction&gt;
        ///      &lt;feature direction=&quot;northNorthWest&quot;&gt;0&lt;/feature&gt;
        ///      &lt;feature direction=&quot;north&quot;&gt;0&lt;/feature&gt;
        ///      &lt;feature direction=&quot;northNorthEast&quot;&gt;0&lt;/feature&gt;
        ///      &lt;feature direction=&quot;eastNorthEast&quot;&gt;0&lt;/feature&gt;
        ///      &lt;feature direction=&quot;east&quot;&gt;0&lt;/feature&gt;
        ///      &lt;feature direction=&quot;eastSouthEast&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cityData {
            get {
                return ResourceManager.GetString("cityData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;carcassonne&gt;
        ///  &lt;tile number=&quot;4&quot;&gt;
        ///
        ///    &lt;cloister id=&quot;0&quot;&gt;
        ///      &lt;texture&gt;cloister&lt;/texture&gt;
        ///    &lt;/cloister&gt;
        ///    &lt;farm id=&quot;1&quot;&gt;
        ///      &lt;texture&gt;farm&lt;/texture&gt;
        ///    &lt;/farm&gt;
        ///
        ///    &lt;direction&gt;
        ///      &lt;feature direction=&quot;northNorthWest&quot;&gt;1&lt;/feature&gt;
        ///      &lt;feature direction=&quot;north&quot;&gt;1&lt;/feature&gt;
        ///      &lt;feature direction=&quot;northNorthEast&quot;&gt;1&lt;/feature&gt;
        ///      &lt;feature direction=&quot;eastNorthEast&quot;&gt;1&lt;/feature&gt;
        ///      &lt;feature direction=&quot;east&quot;&gt;1&lt;/feature&gt;
        ///      &lt;feature direct [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string farmData {
            get {
                return ResourceManager.GetString("farmData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;carcassonne&gt;
        ///  &lt;tile number=&quot;4&quot;&gt;
        ///
        ///    &lt;cloister id=&quot;0&quot;&gt;
        ///      &lt;texture&gt;cloister&lt;/texture&gt;
        ///    &lt;/cloister&gt;
        ///    &lt;farm id=&quot;1&quot;&gt;
        ///      &lt;texture&gt;farm&lt;/texture&gt;
        ///    &lt;/farm&gt;
        ///
        ///    &lt;direction&gt;
        ///      &lt;feature direction=&quot;northNorthWest&quot;&gt;1&lt;/feature&gt;
        ///      &lt;feature direction=&quot;north&quot;&gt;1&lt;/feature&gt;
        ///      &lt;feature direction=&quot;northNorthEast&quot;&gt;1&lt;/feature&gt;
        ///      &lt;feature direction=&quot;eastNorthEast&quot;&gt;1&lt;/feature&gt;
        ///      &lt;feature direction=&quot;east&quot;&gt;1&lt;/feature&gt;
        ///      &lt;feature direct [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string monasteryTest {
            get {
                return ResourceManager.GetString("monasteryTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;carcassonne&gt;
        ///  &lt;tile number=&quot;1&quot;&gt;
        ///
        ///    &lt;city id=&quot;0&quot;&gt;
        ///      &lt;openings&gt;3&lt;/openings&gt;
        ///      &lt;flags&gt;0&lt;/flags&gt;
        ///      &lt;texture&gt;city&lt;/texture&gt;
        ///    &lt;/city&gt;
        ///    &lt;farm id=&quot;1&quot;&gt;
        ///      &lt;neighbor_city&gt;0&lt;/neighbor_city&gt;
        ///      &lt;texture&gt;farm&lt;/texture&gt;
        ///    &lt;/farm&gt;
        ///    &lt;farm id=&quot;2&quot;&gt;
        ///      &lt;neighbor_city&gt;0&lt;/neighbor_city&gt;
        ///      &lt;texture&gt;farm&lt;/texture&gt;
        ///    &lt;/farm&gt;
        ///    &lt;road id=&quot;3&quot;&gt;
        ///      &lt;openings&gt;1&lt;/openings&gt;
        ///      &lt;texture&gt;road&lt;/texture&gt;
        ///    &lt;/road&gt;
        ///
        ///    &lt;direction&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string roadtest {
            get {
                return ResourceManager.GetString("roadtest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Rotation {
            get {
                return ResourceManager.GetStream("Rotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt; 
        ///&lt;carcassonne&gt;
        ///  &lt;tile number=&quot;4&quot;&gt;
        ///
        ///      &lt;cloister id=&quot;0&quot;&gt;
        ///        &lt;texture&gt;cloister&lt;/texture&gt;
        ///      &lt;/cloister&gt;
        ///      &lt;farm id=&quot;1&quot;&gt;
        ///        &lt;texture&gt;farm&lt;/texture&gt;
        ///      &lt;/farm&gt;
        ///
        ///    &lt;direction&gt;
        ///      &lt;feature direction=&quot;northNorthWest&quot;&gt;1&lt;/feature&gt;
        ///      &lt;feature direction=&quot;north&quot;&gt;1&lt;/feature&gt;
        ///      &lt;feature direction=&quot;northNorthEast&quot;&gt;1&lt;/feature&gt;
        ///      &lt;feature direction=&quot;eastNorthEast&quot;&gt;1&lt;/feature&gt;
        ///      &lt;feature direction=&quot;east&quot;&gt;1&lt;/feature&gt;
        ///      &lt;f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tileData {
            get {
                return ResourceManager.GetString("tileData", resourceCulture);
            }
        }
    }
}
